import { FileText } from 'lucide-react';
import type { ModuleConfig } from '../types/module';

export const bdValorizacionesConfig: ModuleConfig = {
  id: 'bd_valorizaciones',
  name: 'BD Valorizaciones',
  subtitle: 'Base de Datos de Valorizaciones',
  description: 'Consulta de valorizaciones en tiempo real',
  icon: FileText,
  rpcFunction: 'buscar_valorizaciones_prod',
  schema: 'cgoii-data-prod',
  tableName: 'bd_valorizaciones',
  fallbackSearchFields: ['proveedor', 'ruc', 'nombre_descripcion'],
  sumField: 'total_aprobado',
  sumLabel: 'Suma Total Aprobado',
  searchPlaceholder: 'Buscar por proveedor, RUC, OS, factura... Prefijos: IE, VAL, MES, GS, OS, RUC, PROV (usa comas para combinar)',
  localStorageKey: 'bd-valorizaciones-column-visibility',
  statusField: 'aprobado',
  pinnedField: 'id_registro',

  dateFields: new Set([
    'mes', 'fecha',
  ]),

  amountFields: new Set([
    'presentado', 'monto_aprobado_arcc', 'saldo_por_aprobar', 'total_aprobado',
  ]),

  recommendedColumns: new Set([
    'id_registro', 'item', 'tipo', 'ie', 'val', 'mes', 'fecha',
    'centro_costos', 'grupo_servicio', 'concepto', 'os',
    'documento_factura', 'ruc', 'proveedor', 'nombre_descripcion',
    'presentado', 'aprobado', 'monto_aprobado_arcc',
    'saldo_por_aprobar', 'total_aprobado', 'comentarios',
  ]),

  columns: [
    { field: 'id_registro', headerName: 'ID', minWidth: 80 },
    { field: 'item', headerName: 'Item', minWidth: 80 },
    { field: 'cod_int', headerName: 'Cód. Interno', minWidth: 110 },
    { field: 'tipo', headerName: 'Tipo', minWidth: 80 },
    { field: 'ie', headerName: 'IE', minWidth: 100 },
    { field: 'val', headerName: 'VAL', minWidth: 80 },
    { field: 'mes', headerName: 'Mes', minWidth: 110 },
    { field: 'fecha', headerName: 'Fecha', minWidth: 110 },
    { field: 'centro_costos', headerName: 'Centro de Costos', minWidth: 150 },
    { field: 'grupo_servicio', headerName: 'Grupo de Servicio', minWidth: 160 },
    { field: 'concepto', headerName: 'Concepto', minWidth: 180 },
    { field: 'os', headerName: 'OS', minWidth: 100 },
    { field: 'documento_factura', headerName: 'Documento / Factura', minWidth: 160 },
    { field: 'ruc', headerName: 'RUC', minWidth: 120 },
    { field: 'proveedor', headerName: 'Proveedor', minWidth: 200 },
    { field: 'nombre_descripcion', headerName: 'Nombre / Descripción', minWidth: 220 },
    { field: 'presentado', headerName: 'Presentado', minWidth: 120 },
    { field: 'aprobado', headerName: 'Aprobado', minWidth: 110 },
    { field: 'observacion_desestimado', headerName: 'Obs. Desestimado', minWidth: 180 },
    { field: 'concepto_2', headerName: 'Concepto 2', minWidth: 150 },
    { field: 'monto_aprobado_arcc', headerName: 'Monto Aprobado ARCC', minWidth: 160 },
    { field: 'dest_aprob_1', headerName: 'Dest. Aprob. 1', minWidth: 130 },
    { field: 'fecha_2', headerName: 'Fecha 2', minWidth: 100 },
    { field: 'val_apb_1', headerName: 'VAL Apb. 1', minWidth: 100 },
    { field: 'dest_aprob_2', headerName: 'Dest. Aprob. 2', minWidth: 130 },
    { field: 'fecha_mes_2', headerName: 'Fecha (Mes) 2', minWidth: 120 },
    { field: 'val_apb_2', headerName: 'VAL Apb. 2', minWidth: 100 },
    { field: 'dest_aprob_3', headerName: 'Dest. Aprob. 3', minWidth: 130 },
    { field: 'fecha_mes_3', headerName: 'Fecha (Mes) 3', minWidth: 120 },
    { field: 'val_apb_3', headerName: 'VAL Apb. 3', minWidth: 100 },
    { field: 'dest_aprob_4', headerName: 'Dest. Aprob. 4', minWidth: 130 },
    { field: 'fecha_mes_4', headerName: 'Fecha (Mes) 4', minWidth: 120 },
    { field: 'val_apb_4', headerName: 'VAL Apb. 4', minWidth: 100 },
    { field: 'saldo_por_aprobar', headerName: 'Saldo por Aprobar', minWidth: 140 },
    { field: 'total_aprobado', headerName: 'Total Aprobado', minWidth: 130 },
    { field: 'comentarios', headerName: 'Comentarios', minWidth: 200 },
    { field: 'nro_pag', headerName: 'Nro. Pág.', minWidth: 90 },
    { field: 'columna_2', headerName: 'Columna 2', minWidth: 100 },
    { field: 'columna_3', headerName: 'Columna 3', minWidth: 100 },
    { field: 'columna_4', headerName: 'Columna 4', minWidth: 100 },
  ],
};
