import { FileText } from 'lucide-react';
import type { ModuleConfig } from '../types/module';

export const pqt06Config: ModuleConfig = {
  id: 'pqt06',
  name: 'PQT06 - Facturas',
  subtitle: 'Maestro de Facturas',
  description: 'Consulta de facturas en tiempo real',
  icon: FileText,
  rpcFunction: 'buscar_documentos_prod',
  schema: 'cgoii-data-prod',
  tableName: 'PQT06_Facturas_Consulta_Master',
  fallbackSearchFields: ['proveedor', 'documento_identidad', 'empresa'],
  sumField: 'total_original',
  sumLabel: 'Suma Total Original',
  searchPlaceholder: 'Buscar por proveedor, RUC, OC, serie-correlativo... (usa comas para combinar)',
  localStorageKey: 'pqt06-column-visibility',
  statusField: 'estado',
  pinnedField: 'id_registro',

  dateFields: new Set([
    'ctl_fecha_evento', 'recepcion', 'fecha_registro', 'fecha_comp', 'fecha_venc',
    'fecha_pago_real', 'as_bd_val_presentacion', 'fecha_doc_rel',
  ]),

  amountFields: new Set([
    'total_original', 'pagado_original', 'financiado_original', 'letras_original',
    'fondo_garantia', 'carta_fianza', 'otras_retenciones', 'total_financiado_5',
    'deducciones', 'pendiente_comp', 'pendiente_deduccion', 'pendiente_letras',
    'pend_total_soles_origen', 'pend_total_dolares',
    'soles_total', 'soles_pagado', 'soles_financiado', 'soles_letras',
    'soles_fondo_garantia', 'soles_carta_fianza', 'soles_otras_retenciones',
    'soles_total_financiado_5', 'soles_deducciones', 'soles_pendiente_comp',
    'soles_pendiente_deduccion', 'soles_pendiente_letras', 'soles_pend_total_final',
    'percepcion', 'perc_emitida', 'suma_percepcion', 'tipo_cambio',
    'total_local', 'total_extranjero',
  ]),

  recommendedColumns: new Set([
    'id_registro', 'ctl_estado', 'ctl_campos_actualizados', 'ctl_fecha_evento',
    'fecha_comp', 'documento_identidad', 'proveedor', 'oc', 'tipo_documento',
    'serie', 'numero_correlativo', 'moneda', 'total_original', 'pagado_original',
    'observaciones', 'concatenar_factura', 'fd_oc_almacen', 'fd_etapa_n2_cod',
    'fd_oc_comprador', 'fd_etapa_n2', 'as_comentarios_procura',
    'as_fee_no_valorizable', 'as_bd_val_presentacion', 'pqt_colegio',
  ]),

  columns: [
    { field: 'id_registro', headerName: 'ID', minWidth: 80 },
    { field: 'ctl_estado', headerName: 'Ctl Estado', minWidth: 100 },
    { field: 'ctl_campos_actualizados', headerName: 'Ctl Campos Actualiz.', minWidth: 160 },
    { field: 'ctl_fecha_evento', headerName: 'Ctl Fecha Evento', minWidth: 120 },
    { field: 'empresa', headerName: 'Empresa', minWidth: 140 },
    { field: 'estado', headerName: 'Estado', minWidth: 120 },
    { field: 'id_estado', headerName: 'ID Estado', minWidth: 90 },
    { field: 'metodo', headerName: 'Método', minWidth: 100 },
    { field: 'recepcion', headerName: 'Recepción', minWidth: 110 },
    { field: 'fecha_registro', headerName: 'Fecha Registro', minWidth: 120 },
    { field: 'fecha_comp', headerName: 'Fecha Comp.', minWidth: 120 },
    { field: 'fecha_venc', headerName: 'Fecha Venc.', minWidth: 120 },
    { field: 'forma_pago', headerName: 'Forma Pago', minWidth: 110 },
    { field: 'dias_pendientes', headerName: 'Días Pend.', minWidth: 100 },
    { field: 'periodo', headerName: 'Periodo', minWidth: 90 },
    { field: 'documento_identidad', headerName: 'RUC/DNI', minWidth: 120 },
    { field: 'proveedor', headerName: 'Proveedor', minWidth: 200 },
    { field: 'proyecto', headerName: 'Proyecto', minWidth: 120 },
    { field: 'oc', headerName: 'OC', minWidth: 100 },
    { field: 'cod_oc', headerName: 'Cód. OC', minWidth: 100 },
    { field: 'unidad_negocio', headerName: 'Unidad Negocio', minWidth: 130 },
    { field: 'id_proveedor', headerName: 'ID Proveedor', minWidth: 110 },
    { field: 'tipo_documento', headerName: 'Tipo Documento', minWidth: 130 },
    { field: 'estado_sunat', headerName: 'Estado SUNAT', minWidth: 120 },
    { field: 'prefijo', headerName: 'Prefijo', minWidth: 80 },
    { field: 'serie', headerName: 'Serie', minWidth: 80 },
    { field: 'numero_correlativo', headerName: 'Nro. Correlativo', minWidth: 120 },
    { field: 'moneda', headerName: 'Moneda', minWidth: 80 },
    { field: 'total_original', headerName: 'Total Original', minWidth: 120 },
    { field: 'pagado_original', headerName: 'Pagado Original', minWidth: 120 },
    { field: 'financiado_original', headerName: 'Financiado Orig.', minWidth: 130 },
    { field: 'letras_original', headerName: 'Letras Original', minWidth: 120 },
    { field: 'fondo_garantia', headerName: 'Fondo Garantía', minWidth: 120 },
    { field: 'carta_fianza', headerName: 'Carta Fianza', minWidth: 110 },
    { field: 'otras_retenciones', headerName: 'Otras Retenc.', minWidth: 120 },
    { field: 'total_financiado_5', headerName: 'Total Financ. 5', minWidth: 120 },
    { field: 'deducciones', headerName: 'Deducciones', minWidth: 110 },
    { field: 'pendiente_comp', headerName: 'Pendiente Comp.', minWidth: 130 },
    { field: 'pendiente_deduccion', headerName: 'Pendiente Deduc.', minWidth: 130 },
    { field: 'pendiente_letras', headerName: 'Pendiente Letras', minWidth: 130 },
    { field: 'pend_total_soles_origen', headerName: 'Pend. Total S/ Orig.', minWidth: 150 },
    { field: 'pend_total_dolares', headerName: 'Pend. Total US$', minWidth: 130 },
    { field: 'soles_total', headerName: 'S/ Total', minWidth: 110 },
    { field: 'soles_pagado', headerName: 'S/ Pagado', minWidth: 110 },
    { field: 'soles_financiado', headerName: 'S/ Financiado', minWidth: 120 },
    { field: 'soles_letras', headerName: 'S/ Letras', minWidth: 110 },
    { field: 'soles_fondo_garantia', headerName: 'S/ Fondo Garantía', minWidth: 140 },
    { field: 'soles_carta_fianza', headerName: 'S/ Carta Fianza', minWidth: 130 },
    { field: 'soles_otras_retenciones', headerName: 'S/ Otras Retenc.', minWidth: 140 },
    { field: 'soles_total_financiado_5', headerName: 'S/ Total Financ. 5', minWidth: 140 },
    { field: 'soles_deducciones', headerName: 'S/ Deducciones', minWidth: 130 },
    { field: 'soles_pendiente_comp', headerName: 'S/ Pend. Comp.', minWidth: 130 },
    { field: 'soles_pendiente_deduccion', headerName: 'S/ Pend. Deduc.', minWidth: 140 },
    { field: 'soles_pendiente_letras', headerName: 'S/ Pend. Letras', minWidth: 130 },
    { field: 'soles_pend_total_final', headerName: 'S/ Pend. Total Final', minWidth: 150 },
    { field: 'percepcion', headerName: 'Percepción', minWidth: 110 },
    { field: 'metodo_percepcion', headerName: 'Método Percepción', minWidth: 140 },
    { field: 'perc_emitida', headerName: 'Perc. Emitida', minWidth: 110 },
    { field: 'periodo_1', headerName: 'Periodo 1', minWidth: 100 },
    { field: 'correlativo_contable', headerName: 'Correlativo Contable', minWidth: 150 },
    { field: 'suma_percepcion', headerName: 'Suma Percepción', minWidth: 130 },
    { field: 'fecha_pago_real', headerName: 'Fecha Pago Real', minWidth: 130 },
    { field: 'id_tc_cancelacion', headerName: 'ID TC Cancelación', minWidth: 140 },
    { field: 'cuenta_cancelacion', headerName: 'Cuenta Cancelación', minWidth: 150 },
    { field: 'corr_cancelacion', headerName: 'Corr. Cancelación', minWidth: 140 },
    { field: 'cuenta_contable', headerName: 'Cuenta Contable', minWidth: 130 },
    { field: 'descripcion_cuenta', headerName: 'Descripción Cuenta', minWidth: 160 },
    { field: 'rubro', headerName: 'Rubro', minWidth: 100 },
    { field: 'cod_prov', headerName: 'Cód. Proveedor', minWidth: 120 },
    { field: 'id_moneda', headerName: 'ID Moneda', minWidth: 90 },
    { field: 'tipo_cambio', headerName: 'Tipo Cambio', minWidth: 110 },
    { field: 'total_local', headerName: 'Total Local', minWidth: 110 },
    { field: 'total_extranjero', headerName: 'Total Extranjero', minWidth: 120 },
    { field: 'id_contable', headerName: 'ID Contable', minWidth: 110 },
    { field: 'usuario_registro', headerName: 'Usuario Registro', minWidth: 130 },
    { field: 'observaciones', headerName: 'Observaciones', minWidth: 200 },
    { field: 'empleado_rendir', headerName: 'Empleado Rendir', minWidth: 130 },
    { field: 'id_empresa', headerName: 'ID Empresa', minWidth: 100 },
    { field: 'sigla_moneda', headerName: 'Sigla Moneda', minWidth: 100 },
    { field: 'nemonico', headerName: 'Nemónico', minWidth: 100 },
    { field: 'cant_anexos', headerName: 'Cant. Anexos', minWidth: 100 },
    { field: 'ind_validez_cpe', headerName: 'Ind. Validez CPE', minWidth: 130 },
    { field: 'id_estado_sunat', headerName: 'ID Estado SUNAT', minWidth: 130 },
    { field: 'fecha_doc_rel', headerName: 'Fecha Doc. Rel.', minWidth: 120 },
    { field: 'tipo_doc_rel', headerName: 'Tipo Doc. Rel.', minWidth: 120 },
    { field: 'serie_doc_rel', headerName: 'Serie Doc. Rel.', minWidth: 120 },
    { field: 'nro_doc_rel', headerName: 'Nro. Doc. Rel.', minWidth: 120 },
    { field: 'concatenar_factura', headerName: 'Concatenar Factura', minWidth: 150 },
    { field: 'fd_oc_almacen', headerName: 'FD OC Almacén', minWidth: 120 },
    { field: 'fd_etapa_n2_cod', headerName: 'FD Etapa N2 Cód.', minWidth: 130 },
    { field: 'fd_oc_comprador', headerName: 'FD OC Comprador', minWidth: 140 },
    { field: 'fd_etapa_n2', headerName: 'FD Etapa N2', minWidth: 120 },
    { field: 'as_comentarios_procura', headerName: 'AS Comentarios Procura', minWidth: 180 },
    { field: 'as_fee_no_valorizable', headerName: 'AS Fee No Valorizable', minWidth: 160 },
    { field: 'as_bd_val_presentacion', headerName: 'AS BD Val. Presentación', minWidth: 170 },
    { field: 'pqt_colegio', headerName: 'PQT Colegio', minWidth: 110 },
  ],
};
